// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjecYzrMttH67ZyizlfOknTcxfdbBEPc4',
    appId: '1:74722692267:web:bf6f9e5ec6efec123b7bee',
    messagingSenderId: '74722692267',
    projectId: 'fir-auth-36368',
    authDomain: 'fir-auth-36368.firebaseapp.com',
    databaseURL: 'https://fir-auth-36368-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-36368.appspot.com',
    measurementId: 'G-KFX2HEGEG1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGQirSLN5VszNj2CWIYCPrLJV2kojqjJU',
    appId: '1:74722692267:ios:87b844d5315a3bc53b7bee',
    messagingSenderId: '74722692267',
    projectId: 'fir-auth-36368',
    databaseURL: 'https://fir-auth-36368-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-36368.appspot.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGQirSLN5VszNj2CWIYCPrLJV2kojqjJU',
    appId: '1:74722692267:ios:87b844d5315a3bc53b7bee',
    messagingSenderId: '74722692267',
    projectId: 'fir-auth-36368',
    databaseURL: 'https://fir-auth-36368-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-36368.appspot.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjecYzrMttH67ZyizlfOknTcxfdbBEPc4',
    appId: '1:74722692267:web:47f78838d27efebb3b7bee',
    messagingSenderId: '74722692267',
    projectId: 'fir-auth-36368',
    authDomain: 'fir-auth-36368.firebaseapp.com',
    databaseURL: 'https://fir-auth-36368-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-36368.appspot.com',
    measurementId: 'G-8D2SK3B24L',
  );
}
